#!/bin/bash

# Usage:
#  data-clean [FILE]...
# or
#  data-clean < infile.csv > outfile.csv
#
# Requires the "sqlite3" package (https://sqlite.org/cli.html).
#
# Performs the following tidy-ups:
#  - Removes duplicate entries (same log data uploaded)
#  - Sort by timestamp
#  - Add session duration column for SessionStop events
#  - Adds a session ID and userToken to all events between SessionStart and SessionStop
#  - Renames columns (removes the json_ prefix)
#  - Adds a "localTime" column (UTC-8)
#

go() {
    cat - data-clean.sql  << SQL_END  | sqlite3
.mode csv
.headers on
.import $1 imported
;

SQL_END
}

go <(cat $*)
