filebeat.inputs:
  - type: tcp
    host: 127.0.0.1:51481
  - type: log
    paths:
      - C:\Users\*\AppData\Roaming\gpii\gpii-20*-*.log

processors:
  # Rename the message field to "json", to match the original metrics
  - rename:
      fields:
        - from: "message"
          to: "json"
  # Parse the data as JSON
  - decode_json_fields:
      fields: ["json"]
  # Remove useless fields
  - drop_fields:
      fields: [ "source", "prospector", "input", "host", "json.level" ]

# Buffer up to 10,000 messages, flushing on every 100, or 5 seconds
queue.mem:
  events: 10000
  flush.min_events: 100
  flush.timeout: 5s

path.data: ${ProgramData:C:\ProgramData}\Morphic\Filebeat
path.logs: ${ProgramData:C:\ProgramData}\Morphic\Filebeat\logs

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["<%host%>:443"]
  protocol: "https"
  username: "<%username%>"
  password: "<%password%>"
  index: "gpii-%{+yyyy.MM.dd}"

setup.template:
  name: 'gpii'
  pattern: 'gpii-*'
  enabled: false
